### ISSUE TITLE
Failed while executing plugin_t.run()

### ISSUE THREAD

**Issue by VoidSec** [VoidSec/DriverBuddy#1]
```
Traceback (most recent call last):
  File "D:/IDA/plugins/DriverBuddy.py", line 43, in run
    driver_type = data.get_driver_id(driver_entry)
  File "D:\IDA/plugins\DriverBuddy\data.py", line 227, in get_driver_id
    real_ddc_addr = locate_ddc(real_driver_entry)
  File "D:\IDA/plugins\DriverBuddy\wdm.py", line 60, in locate_ddc
    prev_instruction = driver_entry_func[0]
IndexError: list index out of range
```

**Comment by VoidSec** [comment]
https://github.com/VoidSec/DriverBuddy/commit/7878c303e320ef41d90a0d6898ab9443f8b09db5
